version: '3'
services:
#mssql docker
  sbt-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Express
    ports:
      - 1401:1433
    networks:
      - sbtnet

  sbt-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=sbt-sql,1433;Database=DBDocker;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 5000:80
    networks:
      - sbtnet
    links:
      - sbt-sql
    depends_on:
      - sbt-sql

networks:
  sbtnet:
    driver: bridge